feat: add sidebar
BeerCodeIndustry/common-frontend pull request #9
Opened 2022-10-19 12:50 UTC by neverwanalive

2022-10-19 13:10 UTC, ordinaryask requested changes

2022-10-19 13:10 UTC, ordinaryask commented on src/lib/theme/animations.ts
> +export const show = (direction: string): Keyframes => keyframes`
prettier on

2022-10-19 13:10 UTC, ordinaryask commented on src/lib/theme/animations.ts
> +export const show = (direction: string): Keyframes => keyframes`
maybe use second arg instead of the same animation

2022-10-19 13:10 UTC, ordinaryask commented on src/lib/core/Sidebar/Sidebar.types.ts
> +  sidebarDirection: Position
better use here 'start' | 'end'

2022-10-19 13:10 UTC, ordinaryask commented on src/lib/core/Sidebar/Sidebar.types.ts
> +  sidebarDirection: Position
and rename to direction

2022-10-19 13:10 UTC, ordinaryask commented on src/lib/theme/animations.ts
> +export const show = (direction: string): Keyframes => keyframes`
i guess "direction" is wrong word for this arg

2022-10-19 13:10 UTC, ordinaryask commented on src/lib/theme/animations.ts
> +export const show = (direction: string): Keyframes => keyframes`
like first arg will be start, second end
0 15.625rem
-15.625rem 0

2022-10-19 13:10 UTC, ordinaryask commented on src/lib/core/Sidebar/Sidebar.component.tsx
> +    <Wrapper
is isOpen=false, sidebar should be closed, but unfortunately we see wrapper

2022-10-19 14:06 UTC, neverwanalive commented on src/lib/theme/animations.ts
> +export const show = (direction: string): Keyframes => keyframes`
не ебет, не работает

2022-10-20 03:38 UTC, ordinaryask approved these changes

2022-10-20 03:38 UTC, merged